### ISSUE TITLE
License of the source code

### ISSUE THREAD

**Issue by Trilarion** [lemon-sherbet/ccleste#11]
Hi, I couldn't find information about the license of the source code in the repository. There does not seem to be a license file or license information in the source files. Is it MIT or GPL or something similar? Adding such information would help clarifying how the code can be used.

**Comment by lemon32767** [comment]
Considering the fact that the original pico-8 cartridge does not have a explicit license (so by omission the original developers own exclusive copyright to it), and the bulk of this project is mostly a line-by-line translation of the original source code, that also bundles graphics & sound assets directly extracted from the game, I do not think adding an open source license would be appropriate, since technically I am infringing copyright.

To be frank, I doubt the original developers care about how you use the code (as long as you aren't selling it or something), and I certainly don't.

As for the fully original source components (such as the SDL frontend code or the makefile), you may consider that to be WTFPL licensed or similar if you wish. 

Copyright law is dumb I think.

**Comment by thearchivalone** [comment]
Thanks for answering this question. I was looking at porting your code to another handheld but lack of license could be bad in my case
