### ISSUE TITLE
SDL_N3DSKeyBind(3DS)

### ISSUE THREAD

**Issue by 0x715C** [lemon-sherbet/ccleste#3]
The function SDL_N3DSKeyBind has been removed upstream, so now the compiler winges about an undefined reference.

Relevant Info
https://github.com/devkitPro/SDL/pull/58
https://github.com/devkitPro/SDL/pull/65

**Comment by lemon32767** [comment]
I fixed that in a new branch: https://github.com/lemon-sherbet/ccleste/commit/ee6cf4d5f22b2694ef656c37d9b9b0ba7de07aa7
However I'm not pushing to master because after updating dkp/3ds-sdl to upstream it seems that the behaviour to wait for VBlank broke or changed within SDL, so the game no longer runs at 30fps as it did before. I haven't been able to make it work correctly even by calling libctru functions directly, so I'm holding out from merging until I can resolve this.

**Comment by lemon32767** [comment]
Fixed with 11563e7f439ed30693578c6b53a62c62ec552d29
